# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pydash_gui.ui'
#
# Created: Thu Jun 18 10:56:21 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_pydash(object):
    def setupUi(self, pydash):
        pydash.setObjectName("pydash")
        pydash.resize(850, 390)
        pydash.setMinimumSize(QtCore.QSize(850, 390))
        self.centralwidget = QtGui.QWidget(pydash)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.game_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_label.sizePolicy().hasHeightForWidth())
        self.game_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.game_label.setFont(font)
        self.game_label.setObjectName("game_label")
        self.gridLayout.addWidget(self.game_label, 3, 0, 1, 1)
        self.ads_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ads_label.sizePolicy().hasHeightForWidth())
        self.ads_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.ads_label.setFont(font)
        self.ads_label.setObjectName("ads_label")
        self.gridLayout.addWidget(self.ads_label, 2, 0, 1, 1)
        self.nick_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nick_label.sizePolicy().hasHeightForWidth())
        self.nick_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.nick_label.setFont(font)
        self.nick_label.setObjectName("nick_label")
        self.gridLayout.addWidget(self.nick_label, 1, 0, 1, 1)
        self.auth_code = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auth_code.sizePolicy().hasHeightForWidth())
        self.auth_code.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.auth_code.setFont(font)
        self.auth_code.setObjectName("auth_code")
        self.gridLayout.addWidget(self.auth_code, 0, 0, 1, 1)
        self.authorize_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorize_button.sizePolicy().hasHeightForWidth())
        self.authorize_button.setSizePolicy(sizePolicy)
        self.authorize_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.authorize_button.setFont(font)
        self.authorize_button.setObjectName("authorize_button")
        self.gridLayout.addWidget(self.authorize_button, 0, 5, 1, 1)
        self.title_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 4, 0, 1, 1)
        self.nick = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nick.sizePolicy().hasHeightForWidth())
        self.nick.setSizePolicy(sizePolicy)
        self.nick.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nick.setFont(font)
        self.nick.setReadOnly(True)
        self.nick.setObjectName("nick")
        self.gridLayout.addWidget(self.nick, 1, 1, 1, 4)
        self.auth_input = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auth_input.sizePolicy().hasHeightForWidth())
        self.auth_input.setSizePolicy(sizePolicy)
        self.auth_input.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auth_input.setFont(font)
        self.auth_input.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.auth_input.setReadOnly(False)
        self.auth_input.setObjectName("auth_input")
        self.gridLayout.addWidget(self.auth_input, 0, 1, 1, 4)
        self.oauth_get = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oauth_get.sizePolicy().hasHeightForWidth())
        self.oauth_get.setSizePolicy(sizePolicy)
        self.oauth_get.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.oauth_get.setFont(font)
        self.oauth_get.setObjectName("oauth_get")
        self.gridLayout.addWidget(self.oauth_get, 1, 5, 1, 1)
        self.chat_connect = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_connect.sizePolicy().hasHeightForWidth())
        self.chat_connect.setSizePolicy(sizePolicy)
        self.chat_connect.setMinimumSize(QtCore.QSize(0, 0))
        self.chat_connect.setBaseSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.chat_connect.setFont(font)
        self.chat_connect.setObjectName("chat_connect")
        self.gridLayout.addWidget(self.chat_connect, 2, 5, 1, 1)
        self.game = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game.sizePolicy().hasHeightForWidth())
        self.game.setSizePolicy(sizePolicy)
        self.game.setMinimumSize(QtCore.QSize(0, 0))
        self.game.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.game.setFont(font)
        self.game.setObjectName("game")
        self.gridLayout.addWidget(self.game, 3, 1, 1, 4)
        self.update_game_title = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_game_title.sizePolicy().hasHeightForWidth())
        self.update_game_title.setSizePolicy(sizePolicy)
        self.update_game_title.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.update_game_title.setFont(font)
        self.update_game_title.setAutoDefault(False)
        self.update_game_title.setDefault(False)
        self.update_game_title.setFlat(False)
        self.update_game_title.setObjectName("update_game_title")
        self.gridLayout.addWidget(self.update_game_title, 3, 5, 4, 1)
        self.dashboard_layout = QtGui.QHBoxLayout()
        self.dashboard_layout.setObjectName("dashboard_layout")
        self.ad_30 = QtGui.QPushButton(self.centralwidget)
        self.ad_30.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_30.sizePolicy().hasHeightForWidth())
        self.ad_30.setSizePolicy(sizePolicy)
        self.ad_30.setMinimumSize(QtCore.QSize(30, 30))
        self.ad_30.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ad_30.setFont(font)
        self.ad_30.setObjectName("ad_30")
        self.dashboard_layout.addWidget(self.ad_30)
        self.ad_60 = QtGui.QPushButton(self.centralwidget)
        self.ad_60.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_60.sizePolicy().hasHeightForWidth())
        self.ad_60.setSizePolicy(sizePolicy)
        self.ad_60.setMinimumSize(QtCore.QSize(30, 30))
        self.ad_60.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ad_60.setFont(font)
        self.ad_60.setObjectName("ad_60")
        self.dashboard_layout.addWidget(self.ad_60)
        self.ad_90 = QtGui.QPushButton(self.centralwidget)
        self.ad_90.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_90.sizePolicy().hasHeightForWidth())
        self.ad_90.setSizePolicy(sizePolicy)
        self.ad_90.setMinimumSize(QtCore.QSize(30, 30))
        self.ad_90.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ad_90.setFont(font)
        self.ad_90.setObjectName("ad_90")
        self.dashboard_layout.addWidget(self.ad_90)
        self.ad_120 = QtGui.QPushButton(self.centralwidget)
        self.ad_120.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_120.sizePolicy().hasHeightForWidth())
        self.ad_120.setSizePolicy(sizePolicy)
        self.ad_120.setMinimumSize(QtCore.QSize(30, 30))
        self.ad_120.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ad_120.setFont(font)
        self.ad_120.setObjectName("ad_120")
        self.dashboard_layout.addWidget(self.ad_120)
        self.ad_150 = QtGui.QPushButton(self.centralwidget)
        self.ad_150.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_150.sizePolicy().hasHeightForWidth())
        self.ad_150.setSizePolicy(sizePolicy)
        self.ad_150.setMinimumSize(QtCore.QSize(30, 30))
        self.ad_150.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ad_150.setFont(font)
        self.ad_150.setObjectName("ad_150")
        self.dashboard_layout.addWidget(self.ad_150)
        self.ad_180 = QtGui.QPushButton(self.centralwidget)
        self.ad_180.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_180.sizePolicy().hasHeightForWidth())
        self.ad_180.setSizePolicy(sizePolicy)
        self.ad_180.setMinimumSize(QtCore.QSize(30, 30))
        self.ad_180.setBaseSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ad_180.setFont(font)
        self.ad_180.setObjectName("ad_180")
        self.dashboard_layout.addWidget(self.ad_180)
        self.gridLayout.addLayout(self.dashboard_layout, 2, 1, 1, 4)
        self.viewer_peak_text = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_peak_text.sizePolicy().hasHeightForWidth())
        self.viewer_peak_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.viewer_peak_text.setFont(font)
        self.viewer_peak_text.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer_peak_text.setObjectName("viewer_peak_text")
        self.gridLayout.addWidget(self.viewer_peak_text, 9, 0, 1, 2)
        self.peak_viewer_number = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peak_viewer_number.sizePolicy().hasHeightForWidth())
        self.peak_viewer_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.peak_viewer_number.setFont(font)
        self.peak_viewer_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.peak_viewer_number.setObjectName("peak_viewer_number")
        self.gridLayout.addWidget(self.peak_viewer_number, 9, 2, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 6)
        self.title = QtGui.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title.setFont(font)
        self.title.setTabChangesFocus(True)
        self.title.setAcceptRichText(False)
        self.title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 4, 1, 3, 4)
        self.viewer_number = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_number.sizePolicy().hasHeightForWidth())
        self.viewer_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.viewer_number.setFont(font)
        self.viewer_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.viewer_number.setObjectName("viewer_number")
        self.gridLayout.addWidget(self.viewer_number, 8, 2, 1, 3)
        self.refresh = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        self.refresh.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.refresh.setFont(font)
        self.refresh.setObjectName("refresh")
        self.gridLayout.addWidget(self.refresh, 5, 0, 1, 1)
        self.viewer_text = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_text.sizePolicy().hasHeightForWidth())
        self.viewer_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.viewer_text.setFont(font)
        self.viewer_text.setAlignment(QtCore.Qt.AlignCenter)
        self.viewer_text.setObjectName("viewer_text")
        self.gridLayout.addWidget(self.viewer_text, 8, 0, 1, 2)
        self.gridLayout.setColumnMinimumWidth(1, 250)
        self.gridLayout.setColumnMinimumWidth(5, 110)
        self.gridLayout.setRowMinimumHeight(0, 30)
        self.gridLayout.setRowMinimumHeight(1, 30)
        self.gridLayout.setRowMinimumHeight(2, 30)
        self.gridLayout.setRowMinimumHeight(3, 30)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.chat_layout = QtGui.QVBoxLayout()
        self.chat_layout.setContentsMargins(0, -1, -1, -1)
        self.chat_layout.setObjectName("chat_layout")
        self.chat_box = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_box.sizePolicy().hasHeightForWidth())
        self.chat_box.setSizePolicy(sizePolicy)
        self.chat_box.setMinimumSize(QtCore.QSize(370, 290))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.chat_box.setFont(font)
        self.chat_box.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.chat_box.setObjectName("chat_box")
        self.chat_layout.addWidget(self.chat_box)
        self.sending_layout = QtGui.QHBoxLayout()
        self.sending_layout.setObjectName("sending_layout")
        self.chat_send = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_send.sizePolicy().hasHeightForWidth())
        self.chat_send.setSizePolicy(sizePolicy)
        self.chat_send.setMinimumSize(QtCore.QSize(320, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.chat_send.setFont(font)
        self.chat_send.setObjectName("chat_send")
        self.sending_layout.addWidget(self.chat_send)
        self.send_message = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_message.sizePolicy().hasHeightForWidth())
        self.send_message.setSizePolicy(sizePolicy)
        self.send_message.setMinimumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.send_message.setFont(font)
        self.send_message.setObjectName("send_message")
        self.sending_layout.addWidget(self.send_message)
        self.chat_layout.addLayout(self.sending_layout)
        self.horizontalLayout.addLayout(self.chat_layout)
        pydash.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(pydash)
        self.statusBar.setObjectName("statusBar")
        pydash.setStatusBar(self.statusBar)

        self.retranslateUi(pydash)
        QtCore.QMetaObject.connectSlotsByName(pydash)

    def retranslateUi(self, pydash):
        pydash.setWindowTitle(QtGui.QApplication.translate("pydash", "PyDash", None, QtGui.QApplication.UnicodeUTF8))
        self.game_label.setText(QtGui.QApplication.translate("pydash", "Game:", None, QtGui.QApplication.UnicodeUTF8))
        self.ads_label.setText(QtGui.QApplication.translate("pydash", "Ads:", None, QtGui.QApplication.UnicodeUTF8))
        self.nick_label.setText(QtGui.QApplication.translate("pydash", "Nick:", None, QtGui.QApplication.UnicodeUTF8))
        self.auth_code.setText(QtGui.QApplication.translate("pydash", "Auth:", None, QtGui.QApplication.UnicodeUTF8))
        self.authorize_button.setText(QtGui.QApplication.translate("pydash", "Get Auth Code", None, QtGui.QApplication.UnicodeUTF8))
        self.title_label.setText(QtGui.QApplication.translate("pydash", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.oauth_get.setText(QtGui.QApplication.translate("pydash", "Authorize", None, QtGui.QApplication.UnicodeUTF8))
        self.chat_connect.setText(QtGui.QApplication.translate("pydash", "Connect to Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.update_game_title.setText(QtGui.QApplication.translate("pydash", "Update Game \n"
"and Title", None, QtGui.QApplication.UnicodeUTF8))
        self.ad_30.setText(QtGui.QApplication.translate("pydash", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.ad_60.setText(QtGui.QApplication.translate("pydash", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.ad_90.setText(QtGui.QApplication.translate("pydash", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.ad_120.setText(QtGui.QApplication.translate("pydash", "120", None, QtGui.QApplication.UnicodeUTF8))
        self.ad_150.setText(QtGui.QApplication.translate("pydash", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.ad_180.setText(QtGui.QApplication.translate("pydash", "180", None, QtGui.QApplication.UnicodeUTF8))
        self.viewer_peak_text.setText(QtGui.QApplication.translate("pydash", "Peak Concurrent:", None, QtGui.QApplication.UnicodeUTF8))
        self.peak_viewer_number.setText(QtGui.QApplication.translate("pydash", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.viewer_number.setText(QtGui.QApplication.translate("pydash", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("pydash", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.viewer_text.setText(QtGui.QApplication.translate("pydash", "Current Viewers:", None, QtGui.QApplication.UnicodeUTF8))
        self.send_message.setText(QtGui.QApplication.translate("pydash", "Send", None, QtGui.QApplication.UnicodeUTF8))

